server:
  port: 7001

spring:
  application:
    name: command-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank_account
      authentication-database: admin
      username: admin
      password: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topic: BankAccountEvents